-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDb7hDQAkc9WCmgLO
Bckn3w5V6oVBOo4pANPp4g+EluygCgYIKoZIzj0DAQehRANCAATwRPRPlEXe7PWB
QeeKM/oSuWkjuIkU4nLCeRoN3FOPmAyA0qHXc2j3WhmfBurgkK8/4mT+FtNWxo6W
kEqxDu/X
-----END PRIVATE KEY-----